.git

__test__
.github
.vscode
containerization/clean-docker-artifacts.sh
containerization/docker-compose.yml
containerization/Dockerfile
containerization/Dockerfile.dockerignore
coverage
node_modules

.env
.env.template
.gitignore
.prettierignore
jest.config.js
LICENSE
README.md
scratch-pad.md
