.git

__test__
.github
.vscode
coverage
node_modules

.containerignore
.env
.env.template
.gitignore
.prettierignore
clean-docker-artifacts.sh
Containerfile
jest.config.js
LICENSE
README.md
scratch-pad.md
