name: workflows_run-test-suite

on:
  push:

  # Make it possible to run the workflow manually (from GitHub's web UI).
  workflow_dispatch:

jobs:

  run-automated-tests:

    runs-on: ubuntu-latest

    outputs:
      line-coverage-percentage: ${{ steps.run-tests.outputs.line-coverage-percentage }}

    steps:
      - name: Check out repository onto runner
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0

      - name: Install dependencies
        run: |
          npm ci
      
      - name: Run tests
        id: run-tests
        run: |
          npm run test -- \
            --coverage \
            --collectCoverageFrom="./src/**" \
              > lines-with-the-coverage-across-All-files.txt
          read -r -a arr <<< $(grep "All files" lines-with-the-coverage-across-All-files.txt)
          echo "line-coverage-percentage=${arr[3]}" >> $GITHUB_OUTPUT
  # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

  report-coverage:

    runs-on: ubuntu-latest

    needs: run-automated-tests

    permissions:
      contents: write

    steps:

      - id: create-badge-url
        name: Create badge with line-coverage-percentage
        run: |
          coverage_percentage="${{ needs.run-automated-tests.outputs.line-coverage-percentage }}%"
          badge_url="![badge-test-coverage](https://img.shields.io/static/v1?label=test-coverage-based-on-lines&message=${coverage_percentage}25&color=black)"
          echo "badge_url=$badge_url" >> $GITHUB_OUTPUT

      # https://github.com/alexanderdamiani/pytester-cov/blame/main/entrypoint.sh
      - name: Post comment (containing line-coverage-percentage badge) on commit
        uses: peter-evans/commit-comment@v3
        with:
          body: ${{ steps.create-badge-url.outputs.badge_url }}
